//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Project
    {
        //DisplayName sets the name from ProjectName to Project (space) Name and etc..
        public int ProjectID { get; set; }
        [DisplayName ("Project Name")]
        public string ProjectName { get; set; }
        [DisplayName ("Project Description")]
        public string ProjectDescription { get; set; }
        [DisplayName ("Project Image")]
        public string ProjectImage { get; set; }
        [DisplayName("GitHub Link")]
        public string GitHubLink { get; set; }
    }
}
